name: dvp_test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dartz: ^0.10.1
  another_flushbar: ^1.12.29
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.18
  crypto_simple: ^1.1.1
  mockito: ^5.3.2
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true