// Mocks generated by Mockito 5.3.2 from annotations
// in dvp_test/test/login_tests/main_test/login_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dvp_test/core/errors/failures.dart' as _i6;
import 'package:dvp_test/core/use_case/use_case.dart' as _i7;
import 'package:dvp_test/features/login/domain/repositories/login_repositoy.dart'
    as _i2;
import 'package:dvp_test/features/login/domain/usecases/fetch_recent_email_use_case.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginRepository_0 extends _i1.SmartFake
    implements _i2.LoginRepository {
  _FakeLoginRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchRecentEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchRecentEmailUseCase extends _i1.Mock
    implements _i4.FetchRecentEmailUseCase {
  MockFetchRecentEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginRepository get loginRepository => (super.noSuchMethod(
        Invocation.getter(#loginRepository),
        returnValue: _FakeLoginRepository_0(
          this,
          Invocation.getter(#loginRepository),
        ),
      ) as _i2.LoginRepository);
  @override
  set loginRepository(_i2.LoginRepository? _loginRepository) =>
      super.noSuchMethod(
        Invocation.setter(
          #loginRepository,
          _loginRepository,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}
